In [6]:
# 1. daca numarul e egal cu suma divizorilor sai minus numarul insusi

def s_div(number: int) -> int:
    divisors: list = [index for index in range(1,number) if number % index == 0]
    return sum(divisors)

def is_x_equal_with_sdiv(x: int) -> bool:
    return (x == s_div(x))
    
def write_all_numbers(n: int) -> None:
    print([index for index in range(n) if is_x_equal_with_sdiv(index)])
    
write_all_numbers(520)


[0, 6, 28, 496]


In [7]:
# 2. Scrieti o functie care determina daca un sir de caractere - presupus a fi scris cu litere mici - este sau nu palindrom. 
# Un palindrom este un sir de caractere care citit de la dreapta la stanga are acelasi continut ca si citirea de la stanga la dreapta.
# In functie de valoarea unui indicator boolean ignore_spaces, avand valoarea implicita False, se vor ignora (elimina) sau nu spatiile.
# Daca sirul dat ca parametru nu are toate literele mici, se va arunca exceptie; 

def is_palindrome (string: str, ignore_spaces: bool = False) -> str:
    '''
    Determines if the given string is palindrome.
    
    :param string: string to be verified
    :param ignore_spaces: determines if spaces are ignored
        
    :return: true if the string is palindrome, else false 
    '''
    if any((character != character.lower()) for character in string):
        raise Exception("Exista litere mari!")
    if ignore_spaces == True:
        string = string.replace(" ", "")
    return string == string[::-1]

is_palindrome('hee e e h')

False

In [6]:
# 3. Functia va returna un tuplu cu: lista de numere care apar in ambele fisiere 
#si diferenta maxima care exista intre numerele din al doilea fisier si numerele din primul fisier.

def common_number_and_max_dif(fis1: str, fis2: str) -> tuple:
    f1 = open(fis1)
    f2 = open(fis2)
    list1 : list = [int(index) for index in f1]
    list2 : list = [int(index) for index in f2]
    list1_set = set(list1)
    list2_set = set(list2)
    return (list1_set.intersection(list2_set), max(list1 + list2) - min(list1 + list2))

common_number_and_max_dif("tema2_fis1.txt", "tema2_fis2.txt")

({1, 5, 6}, 9)

In [13]:
# 4. Sa se scrie o functie sum_divisors_digitscare preia un numar natural strict pozitiv  𝑛  si returneaza suma cifrelor divizorilor sai.
# Intr-o alta functie black_hole se apeleaza in mod repetat sum_divisors_digits pe numerele rezultate, pana cand se atinge un numar 
# maxim de iteratii (implicit 1000) sau se ajunge la numarul 15. Puteti crea alte functii auxiliare.

def get_sum_of_digits(number: int) ->list:
    '''
    Slices the given number into digits and returns their sum.
    
    :param number: the given number to be sliced in digits
        
    :return: the sum of the digits of the given number
    '''
    return sum([int(digit) for digit in str(number)])

def sum_divisors_digitscare(number: int) ->int:
    '''
    Determines the divisors of the given number and calculates the sum of their digits.
    
    :param number: the given number
    
    :return: the sum of the given number's divisors digits
    '''
    divisors: list = [index for index in range(1, number + 1) if number % index == 0]
    return sum([get_sum_of_digits(divisor) for divisor in divisors] )
    
def black_hole(number: int, no_max_of_it: int = 1000) -> None:
    '''
    Calls the function sum_divisors_digitscare while the current number is not 15 and the maximum number of iterations
    haven't been reached.
    
    :param number: the given number
    :param no_max_of_it: the maximum number of iterations
    '''
    it = 0
    while number != 15 and it < no_max_of_it or it == 0:
        number = sum_divisors_digitscare(number)
        it += 1
    print(f'{it} apeluri ale functiei sum_divisors_digitscare')

print(sum_divisors_digitscare(15))
black_hole(15, 5)


15
1 apeluri ale functiei sum_divisors_digitscare


In [2]:
# 5. Sa se scrie o functie care primeste doua dictionare si 
# returneaza True daca primul dictionar este continut in al doilea si False altfel.

def dictionary_in_dictionry(dict1 :dict, dict2 :dict) ->bool:
    return all(item in dict2.items() for item in dict1.items())

geografie1 = {'Romania': 'Bucuresti', 'Serbia': 'Belgrad'}
geografie2 = {'Romania': 'Bucuresti', 'Serbia': 'Belgrad', 'Rusia' : 'Moscova'}
print(dictionary_in_dictionry(geografie1,geografie2))
    

True


In [13]:
# 1. Scrieti o functie care pentru un vector dat  𝑎  dat, returneaza diferenta de ordinul intai intre elementele sale:  𝑏[𝑖]=𝑎[𝑖+1]−𝑎[𝑖] .
# Scrieti apoi o alta functie care face acelasi lucru pentru o matrice, pe linii sau pe coloane.

import numpy as np

def diff1_vector(array: np.array) -> np.array:
    '''
    Determines first degree difference between array's elements.
    
    [a,b,c] => [b-a, c-b] = [b, c] - [a, b] = [1:] - [:-1] = np.diff(np.array)
    
    :param array: the given array 
    
    :return: first degree difference between the given array elements:  𝑏[𝑖]=𝑎[𝑖+1]−𝑎[𝑖] (b - result)
    '''
    return array[1:] - array[:-1]

def diff1_mat(array: np.array, axis: int) -> np.array:
    '''
    Determines first degree difference between array's elements on lines / columns depending on axis. 
    
    axis = 0 => vertical
    [[a, b]  => [a-c, b-d] = [1:,:] - [:-1,:] = np.diff(np.array, axis = 0)
     [c, d]]
     
    axis = 1 => orizontal
    [[a, b]  => [a-b] = [:,1:] - [:,:-1] = np.diff(np.array, axis = 1)
     [c, d]]    [c-d]
     
    :param array: the given array (matrix)
    
    :return: if axis = 0 first degree difference between array's elements on lines, else if axis = 1 between array's elements on columns
    '''
    if axis < 0 or axis > 1:
        raise Exception('\'axis\' must be 1 or 0')
    return array[1:,:] - array[:-1,:] if axis == 0 else array[:,1:] - array[:,:-1]
    
a1 = np.array([1, 2, 10, 3])
a2  = np.array([[1, 2, 3], [40, 50, 60]])

try:
    print('array ', diff1_vector(a1))
    print('matrix (axis = 0) \n', diff1_mat(a2, axis = 0))
    print('matrix (axis = 1) \n', diff1_mat(a2, axis = 1))
except Exception as error:
    print(str(error))

array  [ 1  8 -7]
matrix (axis = 0) 
 [[39 48 57]]
matrix (axis = 1) 
 [[ 1  1]
 [10 10]]


In [1]:
# 2.Sa se scrie o functie care gaseste pozitiile maximelor locale dintr-un vector numpy. 
# Un maxim local este o valoare care are in vecinii imediati (indicele curent  ±1 , fara a iesi din vector) 
# valori strict mai mici decat ea.
import numpy as np

def poz_local_maxim(arr : np.array) -> np.array:
    maxime = np.array([], dtype=np.int)
    if arr[1] < arr[0]:
        maxime = np.append(maxime, 0)
    maxime = np.append(maxime, [i for i in range(1, len(arr) - 1) if (arr[i + 1] < arr[i] and arr[i - 1] < arr[i])])
    if arr[len(arr) - 1] > arr[len(arr) - 2]:
        maxime = np.append(maxime, len(arr) - 1) 
    return maxime

arr = np.array([-1, 3, -7, 1, 2, 6, 0, 1])
poz_local_maxim(arr)

#sau putem folozi funtia din scipy argrelextrema si np.greater din numpy astfel:
#       from scipy.signal import argrelextrema
#       x = np.array([-1, 3, -7, 1, 2, 6, 0, 1])
#       argrelextrema(x, np.greater)

array([1, 5, 7])

In [8]:
# 3. Pentru un vector NumPy dat, sa se calculeze toate ferestrele de o anumita lungime, cu o anumita dilatare. Lungimea unei ferestre
# inseamna numarul de elemente din vectorii rezultati, dilatare reprezinta peste cate elemente vecine se sare in construirea unei 
# "ferestre".

import numpy as np

def get_windows(vector: np.array, win_len: int = 3, dilation: int = 1) -> np.array:
    if win_len < 0 or win_len >= len(vector):
        raise Exception('\'win_len\' cannot be smaller than 0 or higher than the array size')
        
    if dilation <= 0:
        raise Exception('\'dilation\' cannot be 0 or smaller')
        
    interval: int = win_len * dilation
    if interval > len(vector):
         raise Exception('The \'dilation\' must be smaller')
        
    return (np.array( [vector[index : index + interval : dilation] for index in range(len(vector) - interval + dilation)] ))

try:
    print(get_windows(vector = np.arange(20), win_len = 3, dilation = 2))
except Exception as error:
    print(str(error))


[[ 0  2  4]
 [ 1  3  5]
 [ 2  4  6]
 [ 3  5  7]
 [ 4  6  8]
 [ 5  7  9]
 [ 6  8 10]
 [ 7  9 11]
 [ 8 10 12]
 [ 9 11 13]
 [10 12 14]
 [11 13 15]
 [12 14 16]
 [13 15 17]
 [14 16 18]
 [15 17 19]]


In [ ]:
# 4.

In [3]:
# 5.Se da un vector `v` de numere floating point, un numar floating point `x` si un numar intreg `k>0`, `k<=len(v)`. 
# Sa se scrie o functie care determina pozitiile celor mai apropiate `k` valori din `v` fata de `x` (k nearest neighbors, 1d).

import numpy as np

def k_nearest_neighbors(vector: np.array, x: float, k: int) -> np.array:
    if k < 0 or k > len(vector):
        raise Exception('parameter \'k\' invalid')
    indexes_sorted: np.array = np.argsort(np.abs(vector - x))
    return indexes_sorted[:k]

k_nearest_neighbors(vector = np.array([5, 3, 2, -1, 6, 1], dtype = np.float64), x = 0., k = 3)

array([3, 5, 2], dtype=int64)